#cloud-config
users:
  - name: ${username}
    ssh-authorized-keys:
      - ${ssh_public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
  
write_files:
#Salt States
  - encoding: b64
    content: ${salt_reactor_start}
    path: /srv/reactor/start.sls
    permissions: '0644'
    owner: root:salt
  - encoding: b64
    content: ${salt_reactor_delkey}
    path: /srv/reactor/delkey.sls
    permissions: '0644'
    owner: root:salt    
  - encoding: b64
    content: ${salt_zip}
    path: /srv/salt.tgz
    permissions: '0644'
    owner: root:salt

#Master config
  - encoding: b64
    content: ${salt_master_conf}
    path: /etc/salt/master.d/master.conf
    permissions: '0644'
    owner: root:root
  - encoding: b64
    content: ${salt_autosign_key}
    path: /etc/salt/autosign_grains/autosign_key
    permissions: '0644'
    owner: root:root
#Minion config
  - encoding: b64
    content: ${salt_minion_conf}
    path: /etc/salt/minion.d/minion.conf
    permissions: '0644'
    owner: root:root
  - encoding: b64
    content: ${salt_autosign_grains_conf}
    path: /etc/salt/minion.d/autosign-grains.conf
    permissions: '0644'
    owner: root:root

runcmd:
${runcmd}
